# This is a basic workflow to help you get started with Actions

name  : First Workflow
on    : workflow_dispatch
jobs  :
  first-job  :
    runs-on  : windows-2022
    steps    : 
      - name : print greetings
        run  : echo "hello world"
      - name : print goodbye
        run  : echo "Goodbye!!"
